USE QLTG
GO

----------------------------1----------------------------
DROP PROC IF EXISTS USP_getAdminOverview
GO

CREATE 
--ALTER 
PROC USP_getAdminOverview
	@adminid CHAR(10)
AS
BEGIN
	DECLARE @LIST TABLE (ID CHAR(15))
	INSERT @LIST SELECT AUTHORID FROM AUTHOR WHERE ADMINID = @adminid
	SELECT (SELECT COUNT(*) FROM @LIST) AS 'SLTG', (SELECT COUNT(*) FROM EDITOR  WHERE ADMINID = @adminid) AS 'SLBT',
		(SELECT COUNT(*) FROM STORY WHERE AUTHORID IN (SELECT * FROM @LIST) AND STATE = 'ON GOING') AS 'ONPROGRESS', 
		(SELECT COUNT(*) FROM STORY WHERE AUTHORID IN (SELECT * FROM @LIST) AND STATE = 'DONE') AS 'DONE'
END
GO

--EXEC USP_getAdminOverview @adminid = 'AD342720  '
--SELECT * FROM AUTHOR WHERE ADMINID = 'AD342720  '
--SELECT * FROM STORY WHERE AUTHORID = 'AU0886539 '
--SELECT * FROM STORY WHERE AUTHORID = 'AU2024405 ' 
--SELECT * FROM STORY WHERE AUTHORID = 'AU2563038 '
--SELECT * FROM STORY WHERE AUTHORID = 'AU2671764 '
--SELECT * FROM STORY WHERE AUTHORID = 'AU4101314 '

----------------------------2----------------------------
DROP PROC IF EXISTS USP_getAllAccounts 
GO

CREATE 
--ALTER 
PROC USP_getAllAccounts
	@adminid CHAR(10)
AS
BEGIN
	IF NOT EXISTS (SELECT AUTHORID FROM AUTHOR  WHERE ADMINID = @adminid)
	AND NOT EXISTS (SELECT EDITORID FROM EDITOR  WHERE ADMINID = @adminid)
		BEGIN
			SELECT 'ADMIN HAS NO AUTHOR, ADMIN' ERROR
			RETURN 0
		END
	DECLARE @LIST TABLE(ID CHAR(15), NAME CHAR(50), AVATAR VARCHAR(50), TYPE CHAR(10))
	INSERT @LIST SELECT AUTHORID, AUTHORNAME, AVATAR, 'AUTHOR' AS 'TYPE' FROM AUTHOR  WHERE ADMINID = @adminid
	INSERT @LIST SELECT EDITORID, EDITORNAME, AVATAR, 'EDITOR' AS 'TYPE' FROM EDITOR	WHERE ADMINID = @adminid
	SELECT * FROM @LIST
END
GO

--EXEC USP_getAllAccounts @adminid = 'AD342720  '

----------------------------3----------------------------
DROP PROC IF EXISTS USP_getAllAuthors 
GO

CREATE 
--ALTER 
PROC USP_getAllAuthors
	@adminid CHAR(10)
AS
BEGIN 
	IF NOT EXISTS (SELECT AUTHORID FROM AUTHOR  WHERE ADMINID = @adminid)
	AND NOT EXISTS (SELECT EDITORID FROM EDITOR  WHERE ADMINID = @adminid)
		BEGIN
			SELECT 'ADMIN HAS NO AUTHOR' ERROR
			RETURN 0
		END

	DECLARE @AUTHORS TABLE (AUTHORID CHAR(10), AUTHORNAME NCHAR(50), PENNAME CHAR(20), AVATAR CHAR(50), SLT INT, SLC INT)
	INSERT @AUTHORS SELECT AU.AUTHORID, AU.AUTHORNAME, AU.USERNAME AS 'PENNAME', AVATAR, (SELECT COUNT(*) FROM STORY WHERE AUTHORID = AU.AUTHORID) AS 'SLT', (SELECT SUM(NUMOFCHAPS) FROM STORY WHERE AUTHORID = AU.AUTHORID) AS 'SLC'
					FROM AUTHOR AU WHERE AU.ADMINID = @adminid
	UPDATE @AUTHORS
	SET SLC = 0 WHERE SLC IS NULL
	SELECT * FROM @AUTHORS	
END 
GO

--SELECT * FROM AUTHOR WHERE AUTHORID IN (SELECT AUTHORID FROM @T) 
--EXEC USP_getAllEditors @adminid = 'AD342720'
--SELECT * FROM EDITOR WHERE ADMINID = 'AD342720' 
--select * from story where EDITORID = 'ED779066' or EDITORID = 'ED949502'

----------------------------4----------------------------
DROP PROC IF EXISTS USP_getAllEditors
GO

CREATE 
--ALTER 
PROC USP_getAllEditors
	@adminid CHAR(10)
AS
BEGIN 
	IF NOT EXISTS (SELECT EDITORID FROM EDITOR  WHERE ADMINID = @adminid)
		BEGIN
			SELECT 'ADMIN HAS NO EDITOR' ERROR
			RETURN 0
		END

	SELECT E.EDITORID, E.EDITORNAME, E.USERNAME AS 'PENNAME', AVATAR, (SELECT COUNT(*) FROM AUTHOR AU WHERE EDITORID = E.EDITORID) AS 'SLTG', (SELECT COUNT(*) FROM STORY WHERE EDITORID = E.EDITORID) AS 'SLT'
	FROM EDITOR E WHERE E.ADMINID = @adminid
	--GROUP BY E.EDITORID, E.EDITORNAME
END 
GO

--EXEC USP_getAllEditors @adminid = 'AD342720    '
--SELECT COUNT(*) FROM STORY WHERE EDITORID = 'ED785700      '
--SELECT COUNT(*) FROM AUTHOR WHERE EDITORID = 'ED785700      '

----------------------------5----------------------------
DROP PROC IF EXISTS USP_getAllStories
GO

CREATE 
--ALTER 
PROC USP_getAllStories
	@adminid CHAR(10)
AS
BEGIN
	IF NOT EXISTS (SELECT AUTHORID FROM AUTHOR  WHERE ADMINID = @adminid)
		BEGIN
			SELECT 'ADMIN HAS NO AUTHOR' ERROR
			RETURN 0
		END

	DECLARE @LIST TABLE(ID CHAR(15))
	INSERT @LIST SELECT AUTHORID FROM AUTHOR  WHERE ADMINID = @adminid

	IF NOT EXISTS (SELECT S.STORYID	FROM STORY S WHERE S.AUTHORID IN (SELECT * FROM @LIST))
		BEGIN
			SELECT 'AUTHORS HAS NO STORY ' ERROR
			RETURN 0
		END

	SELECT S.STORYID, S.STORYNAME, S.NUMOFCHAPS, S.AVATAR, 'Chapters' AS 'PROCESS'
	FROM STORY S WHERE S.AUTHORID IN (SELECT * FROM @LIST)
END 
GO

--EXEC USP_getAllStories @adminid = 'AD342720  '
--SELECT * FROM STORY WHERE STORYID NOT IN (SELECT STORYID FROM CHAPTER)
--SELECT * FROM STORY WHERE STORYID NOT IN (SELECT STORYID FROM OUTLINE)
--SELECT * FROM STORY WHERE STORYID NOT IN (SELECT STORYID FROM DRAFT)


----------------------------6----------------------------
DROP PROC IF EXISTS USP_createAdmin
GO

CREATE 
--ALTER 
PROC USP_createAdmin
	@adminid CHAR(10),
	@username CHAR(20),
	@password CHAR(15)
AS
BEGIN 
	IF EXISTS (SELECT ADMINID FROM ADMIN WHERE TRIM(ADMINID) = TRIM(@adminid))
		BEGIN
			SELECT 'ID IS EXISTED' AS 'ERROR'
			ROLLBACK TRAN
			RETURN 0
		END

	INSERT ADMIN (ADMINID, PASSWORD, USERNAME, AVATAR) 
	VALUES (@adminid, @password, @username, 'empty.png')
	SELECT 'ADDING ADMIN SUCCESSFULLY' AS '1'
END
GO

----------------------------7----------------------------
DROP PROC IF EXISTS USP_createAuthor
GO

CREATE 
--ALTER 
PROC USP_createAuthor
	@authorid CHAR(10),
	@adminid CHAR(10),
	@username CHAR(20),
	@password CHAR(15)
AS
BEGIN
	IF EXISTS (SELECT AUTHORID FROM AUTHOR WHERE TRIM(AUTHORID) = TRIM(@authorid))
		BEGIN
			SELECT 'ID IS EXISTED' AS 'ERROR'
			ROLLBACK TRAN
			RETURN 0
		END

	INSERT AUTHOR (AUTHORID, ADMINID, PASSWORD, USERNAME, AVATAR) 
	VALUES (@authorid, @adminid, @password, @username, 'empty.png')
	SELECT 'ADDING AUTHOR SUCCESSFULLY' AS '1'
END
GO

----------------------------8----------------------------
DROP PROC IF EXISTS USP_createEditor
GO

CREATE 
--ALTER 
PROC USP_createEditor
	@editorid CHAR(10),
	@adminid CHAR(10),
	@username CHAR(20),
	@password CHAR(15)
AS
BEGIN 
	IF EXISTS (SELECT EDITORID FROM EDITOR WHERE TRIM(EDITORID) = TRIM(@editorid))
		BEGIN
			SELECT 'ID IS EXISTED' AS 'ERROR'
			ROLLBACK TRAN
			RETURN 0
		END

	INSERT EDITOR (EDITORID, ADMINID, PASSWORD, USERNAME, AVATAR) 
	VALUES (@editorid, @adminid, @password, @username, 'empty.png')
	SELECT 'ADDING EDITOR SUCCESSFULLY' AS '1'
END
GO

----------------------------9----------------------------
DROP PROC IF EXISTS USP_deleteAdmin
GO

CREATE 
--ALTER 
PROC USP_deleteAdmin
	@adminid CHAR(10)
AS
BEGIN 
	IF NOT EXISTS (SELECT ADMINID FROM ADMIN WHERE TRIM(ADMINID) = TRIM(@adminid))
		BEGIN
			SELECT 'ID IS NOT EXIST' AS 'ERROR'
			ROLLBACK TRAN
			RETURN 0
		END

	DELETE FROM ADMIN WHERE TRIM(ADMINID) = TRIM(@adminid)
	SELECT 'DELETE ADMIN ' + @adminid + ' SUCCESSFULLY' AS '1'
END
GO

----------------------------10----------------------------
DROP PROC IF EXISTS USP_deleteAuthor
GO

CREATE 
--ALTER 
PROC USP_deleteAuthor
	@authorid CHAR(10)
AS
BEGIN
	IF NOT EXISTS (SELECT AUTHORID FROM AUTHOR WHERE TRIM(AUTHORID) = TRIM(@authorid))
		BEGIN
			SELECT 'ID IS NOT EXIST' AS 'ERROR'
			ROLLBACK TRAN
			RETURN 0
		END

	DELETE FROM AUTHOR WHERE TRIM(AUTHORID) = TRIM(@authorid)
	SELECT 'DELETE AUTHOR ' + @authorid + ' SUCCESSFULLY' AS '1'
END	
GO

----------------------------11----------------------------
DROP PROC IF EXISTS USP_deleteEditor
GO

CREATE 
--ALTER 
PROC USP_deleteEditor
	@editorid CHAR(10)
AS
BEGIN 
	IF NOT EXISTS (SELECT EDITORID FROM EDITOR WHERE TRIM(EDITORID) = TRIM(@editorid))
		BEGIN
			SELECT 'ID IS NOT EXIST' AS 'ERROR'
			ROLLBACK TRAN
			RETURN 0
		END

	DELETE FROM EDITOR WHERE TRIM(EDITORID) = TRIM(@editorid)
	SELECT 'DELETE EDITOR ' + @editorid + ' SUCCESSFULLY' AS '1'
END
GO

----------------------------12----------------------------
DROP PROC IF EXISTS USP_getAuthorFromEditor 
GO

CREATE 
--ALTER 
PROC USP_getAuthorFromEditor
	@editorid CHAR(10)
AS
BEGIN
	IF NOT EXISTS (SELECT AUTHORID FROM AUTHOR WHERE EDITORID = @editorid)
		BEGIN
			SELECT 'EDITOR HAS NO AUTHOR' AS 'ERROR'
			RETURN 0
		END

	DECLARE @AUTHORS TABLE (AUTHORID CHAR(10), AUTHORNAME NCHAR(50), PENNAME CHAR(20), AVATAR CHAR(50), SLT INT, SLC INT)
	INSERT @AUTHORS SELECT AU.AUTHORID, AU.AUTHORNAME, AU.USERNAME AS 'PENNAME', AVATAR, (SELECT COUNT(*) FROM STORY WHERE AUTHORID = AU.AUTHORID) AS 'SLT', 
					(SELECT SUM(NUMOFCHAPS) FROM STORY WHERE AUTHORID = AU.AUTHORID) AS 'SLC'
					FROM AUTHOR AU WHERE AU.EDITORID = @editorid
	UPDATE @AUTHORS
	SET SLC = 0 WHERE SLC IS NULL
	SELECT * FROM @AUTHORS	
END
GO

--EXEC USP_getAllEditors @adminid = 'AD342720'
--EXEC USP_getAuthorFromEditor @editorid = 'ED949502'

----------------------------13----------------------------
DROP PROC IF EXISTS USP_calPaidUnpaidStory
GO

create 
--alter
proc USP_calPaidUnpaidStory
	@storyid char(10)
as
begin
	declare @gia float = 0, @unpair float = 0
	select @gia = @gia + ISNULL(SUM(GIA), 0 ), @unpair = @unpair + ISNULL(SUM(UNPAIR), 0 ) from CHAPTER where STORYID = @storyid
	select @gia = @gia + ISNULL(SUM(GIA), 0 ), @unpair = @unpair + ISNULL(SUM(UNPAIR), 0 ) from OUTLINE where STORYID = @storyid
	select @gia = @gia + ISNULL(SUM(GIA), 0 ), @unpair = @unpair + ISNULL(SUM(UNPAIR), 0 ) from DRAFT where STORYID = @storyid
	select @unpair unpaid, (@gia - @unpair) paid
end
go

--EXEC USP_getAuthorFromEditor @editorid = 'ED779066  '
--EXEC countStory 'AU6873987      '
--EXEC storydatalist 'AU0886539  '
--EXEC USP_calPaidUnpaidStory 'ST188007    '

----------------------------14----------------------------
DROP PROC IF EXISTS USP_storyDataList
GO

create 
--alter
proc USP_storyDataList
	@authorid char(10)
as
begin
	if not exists (select STORYID from STORY where AUTHORID = @authorid)
	begin
		SELECT 'AUTHOR HAS NO STORY ' ERROR
		return 0
	end

	select STORYID storyid, STORYNAME name, AVATAR avt, NUMOFCHAPS numofchaps,
	STATE process, NUMOFCHAPS approve from STORY
	where AUTHORID = @authorid
end
go





